maxJobs: 200

manifest: 'somatic-conda/tests/data/pairs_test.txt'
inputDir: 'somatic-conda/tests/data'
outputDir: 'output'
logDir: 'logs'
tempDir: 'TMP'
execDir: 'somatic-conda'

bedFile: 'somatic-conda/tests/data/test.bed'
dbSNP: 'somaticseq2_resource_bundle/hg19/dbsnp_138.hg19.vcf.gz'
COSMIC: 'somaticseq2_resource_bundle/hg19/cosmic_hg19_v85.vcf.gz'
PON: 'NA'
refGenome: 'somaticseq2_resource_bundle/hg19/hg19_canonical_correct_chr_order.fa'
refGenomeDict: 'somaticseq2_resource_bundle/hg19/hg19_canonical_correct_chr_order.dict'

LofreqBamPrepare: TRUE
PonPrepare: TRUE

useSomaticCombiner: TRUE
mergeTag: PASS
useMutect2: TRUE       
useMuse: TRUE
useLofreq: TRUE
useStrelka: TRUE
useVardict: TRUE
VardictSplit: FALSE 
useTNsnv: FALSE 

useVarscan: FALSE 
useSniper: FALSE 
useSentieon: FALSE

GATK: /DCEG/Projects/Exome/SequencingData/GATK_binaries/GenomeAnalysisTK-3.8-1-0-gf15c1c3ef/GenomeAnalysisTK.jar
Lofreq: /DCEG/CGF/Bioinformatics/software/lofreq_star-2.1.3.1/bin/lofreq
LofreqDir: Lofreq
Strelka: /DCEG/CGF/Bioinformatics/software/strelka-2.9.2.centos6_x86_64/bin/configureStrelkaSomaticWorkflow.py
Manta: /DCEG/CGF/Bioinformatics/software/manta-1.5.0.centos6_x86_64/bin/configManta.py
MantaDir: Manta
StrelkaDir: Strelka
Mutect2: /DCEG/CGF/Bioinformatics/Analysi/public_v2/GenomeAnalysisTK-3.7.jar
Mutect2Dir: Mutect2
Sentieon: /DCEG/Resources/Tools/goldenhelix/sentieon-genomics-201808.03/bin/sentieon
SentieonDir: Sentieon
Muse: /DCEG/CGF/Bioinformatics/software/MuSE/MuSE
MuseDir: Muse
VarDict: /DCEG/CGF/Bioinformatics/software/VarDict
VardictDir: Vardict
VardictMAF: 0.01
VarScan: /DCEG/CGF/Bioinformatics/software/VarScan.v2.3.9.jar
VarscanDir: Varscan
SniperDir: Sniper
SomaticCombiner: somatic-conda/files/somaticCombiner.jar

Mutect: /DCEG/CGF/Bioinformatics/Analysis/public_v2/mutect-1.1.7.jar

GATK4: /DCEG/CGF/Bioinformatics/software/gatk-4.1.3.0/gatk 
artifactMode: 'G/T'
Mutect2Dir4: 'GATK4Mutect2'
